const types = {
	'LOAD_TODOS': 'LOAD_TODOS',
	'SUBMIT_TODO': 'SUBMIT_TODO',
	'DELETE_TODO': 'DELETE_TODO',
	'UNDELETE_TODO': 'UNDELETE_TODO',
	'INPUT_CHANGED': 'INPUT_CHANGED'
};

export default types;